server:
  port: 8000

spring:
  datasource:
    name:
    url: jdbc:mysql://127.0.0.1:3306/yxl?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456